
interface MetaData {
    environment: string,
    platformId: string
}

interface LogoImage {
    key: null,
    props: Record<string, string>,
    _onwer: string,
    _store: Record<string, string>
}

interface Credentials {
    publicKey: string,
    secretKey: string,
    logo: LogoImage
    additionalMetadata: MetaData
}

interface VideoConfig {
    encodingTier: string,
    playbackPolicy: Array<string>
}

interface PlatformCredentials {
    id: string,
    name: string,
    credentials: Credentials,
    config?: VideoConfig
}

const fetchApiVideoMedia = async (sourcePlatform: PlatformCredentials) => {
    const credentials = sourcePlatform?.credentials ? sourcePlatform.credentials : null;

    const videos: any[] = [];
    let currentPage = 1;
    let pagesTotal = 1;

    try {
        do {
            const response = await fetch(`https://sandbox.api.video/videos?currentPage=${currentPage}&pageSize=25`, {
                method: 'GET',
                headers: {
                    'Authorization': `Bearer ${credentials?.secretKey ? credentials.secretKey : null}`,
                    'Content-Type': 'application/json',
                },
            });

            if (!response.ok) {

                return { success: false, message: "Failed to fetch video from API Video" };
            }

            const res = await response.json();
            videos.push(...res.data);
            pagesTotal = res.pagination.pagesTotal;
            currentPage++;

        } while (currentPage <= pagesTotal);

        return {
            success: true,
            response: { data: videos },
        };
    } catch (error) {
        return { success: false, message: error?.message ?? "Failed to fetch video from API Video" };
    }
};

// create media in fastpix
const createMedia = async (destinationPlatform: PlatformCredentials, mp4_support: string, videoId: string, tags: Array<string>) => {
    const credentials = destinationPlatform?.credentials ? destinationPlatform.credentials : null;
    const url = 'https://v1.fastpix.io/on-demand';

    const config = destinationPlatform?.config ? destinationPlatform.config : null;
    const autoGeneratedCaptions = config?.autoGenerateCaptions == "1" ? true : false;
    const maxResolutionTier = config?.maxResolutionTier ? config.maxResolutionTier : null;
    const playbackPolicy = config?.playbackPolicy?.length === 1 ? "public" : "private";
    const testmode = config?.testMode ? config.testMode : null;

    const requestBody = {
        metadata: {
            "APIvideoId": videoId,
        },
        accessPolicy: playbackPolicy,
        maxResolution: maxResolutionTier,
        inputs: [
            {
                type: 'video',
                url: `${mp4_support}`,
                ...(testmode === "1" ? { startTime: 0, endTime: 10 } : {})
            },
        ],
        mp4Support: "capped_4k",
    };

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'Authorization': 'Basic ' + Buffer.from(`${credentials?.publicKey ? credentials.publicKey : null}:${credentials?.secretKey ? credentials.secretKey : null}`).toString('base64')
            },
            body: JSON.stringify(requestBody),
        });

        if (response.ok) {

            return await response.json();

        } else {

            return { success: false, message: "Failed to create media in fastpix" }
        }
    } catch (error) {

        return { success: false, message: error?.message ?? "Failed to create media in fastpix" }
    }
};

// API Video migration endpoint
export default async function POST(request: Request) {
    const data = await request.json();
    const sourcePlatform = data?.sourcePlatform ? data.sourcePlatform : null;
    const destinationPlatform = data?.destinationPlatform ? data?.destinationPlatform : null;

    const result = await fetchApiVideoMedia(sourcePlatform);

    if (!result.success) {
        return new Response(JSON.stringify({ message: 'Failed to fetch media from API Video' }), { status: 400 });
    }

    const videos = result.response.data; // all media of api video
    const createdMedia = [];
    const failedToCreateMedia = [];

    for (const video of videos) {
        if (video?.assets?.mp4 !== "none") {
            const mp4_support = video?.assets?.mp4;
            const videoId = video?.videoId;
            const tags = video?.tags ? video.tags : null;

            const createdMediaEntry = await createMedia(destinationPlatform, mp4_support, videoId, tags);
            if (!createdMediaEntry.success) {

                failedToCreateMedia.push([videoId]);
            } else {

                createdMedia.push(createdMediaEntry);
            }
        }
    }

    if (createdMedia.length > 0) {

        return new Response(JSON.stringify({ success: true, createdMedia, failedToCreateMedia }), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });
    } else {

        return new Response(JSON.stringify({ error: 'No media were created' }), { status: 400 });
    }
}
